apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nordmart-st
  namespace: argocd
spec:
  destination:
    namespace: nordmart-st
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-st/nordmart/st
    repoURL: 'https://github.com/stakater/nordmart-apps-config.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      automated:
        prune: true
        selfHeal: true
      prune: true
      selfHeal: true
