apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nordmart-prod
  namespace: argocd
spec:
  destination:
    namespace: nordmart-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: 04-prod/nordmart/prod
    repoURL: 'https://github.com/stakater/nordmart-apps-config.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      automated:
        prune: true
        selfHeal: true
      prune: true
      selfHeal: true
